### ISSUE TITLE
language-selector not work

### ISSUE THREAD

**Issue by Moon-DaeSeung** [notionpresso/docs#23]

**Comment by anonymousRecords** [comment]
Could you provide more details about this issue?

1. Set the language based on the user's region upon initial access.

https://github.com/user-attachments/assets/4d1b8f6b-9493-47b3-80ea-6e36216c6478

2. Change the language using the Language Selector.

https://github.com/user-attachments/assets/eeeeef02-28ea-4915-96d6-ad750292cdf4

**Comment by Moon-DaeSeung** [comment]
oh now It works ㅎㅎ;;
