### ISSUE TITLE
Dragging issue with animations on mobile landing pages

### ISSUE THREAD

**Issue by anonymousRecords** [notionpresso/docs#5]
https://github.com/user-attachments/assets/9470f241-88dc-46d1-b775-6bd97dbf9ed0

As you can see in the attached video, when accessing the official document site on **mobile devices**, the drag animations do not operate smoothly. 
Additionally, the animations are also not smooth on **desktops**, and they need to be fixed.

**Comment by anonymousRecords** [comment]
Due to the change in the library name, I also considering modifying the entire structure of the landing page.

**Comment by Moon-DaeSeung** [comment]
resolved
